dataset_path: datasets/mof_synthesis_4.npz
exp_name: mof_synthesis_4_mse

epochs: 50
batch_size: 1000
lr: 0.001
weight_decay: 0.0085
val_n: 100
test_n: 100
seed: 42

hidden: 128
num_layers: 1
grad_clip: 1.0

teacher_forcing: true
tf_every: 50
tf_drop_epoch: 250

scaffold: mof_synthesis_4

theta_lo: 1.0e-3
theta_hi: 2.0

n_substeps: 1

study: mof_synthesis_mse

ckpt_every: 5    # save checkpoint every 5 epochs (0 = disable)

model_class: ode_rnn_2020
