dataset_path: datasets/N1000_T300_steps600_zeros_knoise0.0_reduced6_ADGJLM.npz
exp_name: 6eq_ADGJLM_50ep_logmse_loss_substeps10

epochs: 50
batch_size: 1000
lr: 0.001
weight_decay: 0.0085
val_n: 100
test_n: 100
seed: 42

hidden: 128
num_layers: 1
grad_clip: 1.0

teacher_forcing: true
tf_every: 50
tf_drop_epoch: 250

scaffold: reduced6_ADGJLM

theta_lo: 1.0e-3
theta_hi: 2.0

n_substeps: 10

study: loss_study

ckpt_every: 10    # save checkpoint every 5 epochs (0 = disable)